swagger: '2.0'
info:
  version: '1.0.0'
  title: TMN Payment Gateway - Transfer Service
  description: A transfer API for transfering money. Use swagger-2.0 specification
  termsOfService: http://TBD/terms/
  contact:
    name: Payment Gateway API team
    email: foo@example.com
    url: http://TBD
  license:
    name: TBD
    url: http://TBD
host: TBD
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /transfer:
    post:
      description: create trasfer
      operationId: createTransfer
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: xref
          in: query
          description: external reference for transferrer e.g. merchant ref
          required: false
          type: string
        - name: recipient
          in: query
          description: The id of recipient the transfer was sent to
          required: false
          type: string
        - name: amount
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: transfer response
          schema:
            properties:
              transfer_id:
                type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

  /transfer/{id}:
    get:
      description: Returns a specific transfer id
      operationId: findTransferById
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: id
          in: path
          description: ID of transfer fetch
          required: true
          type: string
      responses:
        '200':
          description: transfer object response
          schema:
            $ref: '#/definitions/transfer'
        '404':
          description: Entity not found.
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  transfer:
    type: object
    required:
      - transfer_id
    properties:
      transfer_id:
        type: string
      tag:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
